// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGl6nTgOXLo2TaOYXFQ87wYpGgP8cHVms',
    appId: '1:459624501765:web:db3e07ed067ce612d4426c',
    messagingSenderId: '459624501765',
    projectId: 'e-commerce-3ab20',
    authDomain: 'e-commerce-3ab20.firebaseapp.com',
    storageBucket: 'e-commerce-3ab20.appspot.com',
    measurementId: 'G-MR4Q52SMCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WaNQLJXBeOyYUWI81lgPg7QkF61AS7Y',
    appId: '1:459624501765:android:046fd43ae5e896c9d4426c',
    messagingSenderId: '459624501765',
    projectId: 'e-commerce-3ab20',
    storageBucket: 'e-commerce-3ab20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqXgEF7v-No3IRpbPUxZl0VXm9qtb68K8',
    appId: '1:459624501765:ios:871c060fabe40f51d4426c',
    messagingSenderId: '459624501765',
    projectId: 'e-commerce-3ab20',
    storageBucket: 'e-commerce-3ab20.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqXgEF7v-No3IRpbPUxZl0VXm9qtb68K8',
    appId: '1:459624501765:ios:871c060fabe40f51d4426c',
    messagingSenderId: '459624501765',
    projectId: 'e-commerce-3ab20',
    storageBucket: 'e-commerce-3ab20.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGl6nTgOXLo2TaOYXFQ87wYpGgP8cHVms',
    appId: '1:459624501765:web:a7af73681a5afa88d4426c',
    messagingSenderId: '459624501765',
    projectId: 'e-commerce-3ab20',
    authDomain: 'e-commerce-3ab20.firebaseapp.com',
    storageBucket: 'e-commerce-3ab20.appspot.com',
    measurementId: 'G-DBCG4RCS4W',
  );
}
